name: Build NetHunter Kernel for Redmi 9C NFC

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4

      - name: Set Up Dependencies
        run: |
          sudo apt update
          sudo apt install -y bc bison flex libssl-dev curl make build-essential

      - name: Download and Set Up Toolchains
        run: |
          # Download Linaro GCC 4.9
          mkdir -p /opt/gcc
          cd /opt/gcc
          curl -LO "https://kali.download/nethunter-images/toolchains/linaro-aarch64-4.9.tar.xz"
          tar -xf linaro-aarch64-4.9.tar.xz --strip-components=1
          rm -rf linaro-aarch64-4.9.tar.xz

          # Export toolchain paths
          echo "export PATH=/opt/gcc/bin:$PATH" >> ~/.bashrc
          echo "export ARCH=arm64" >> ~/.bashrc
          echo "export CROSS_COMPILE=/opt/gcc/bin/aarch64-linux-gnu-" >> ~/.bashrc
#          echo "export CC=clang" >> ~/.bashrc
          source ~/.bashrc

      - name: Manually Install Python 2
        run: |
          curl -O https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz
          tar -xf Python-2.7.18.tgz
          cd Python-2.7.18
          ./configure --prefix=/usr/local
          make -j$(nproc)
          sudo make altinstall
          sudo ln -sf /usr/local/bin/python2.7 /usr/bin/python

      - name: Build Kernel
        run: |
          export PATH=/opt/gcc/bin:$PATH
          export ARCH=arm64
          export CROSS_COMPILE=/opt/gcc/bin/aarch64-linux-gnu-
 #         export CC=clang
          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8
          make clean && make mrproper
          make angelican_defconfig
          make -j$(nproc) V=1

      - name: Package Kernel
        run: |
          mkdir -p output
          if [ -f arch/arm64/boot/Image.gz-dtb ]; then
            cp arch/arm64/boot/Image.gz-dtb output/
            echo "✅ Kernel Build Completed Successfully!"
          else
            echo "❌ Kernel Image not found!" && exit 1
          fi

      - name: Upload Kernel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sakurajima_Nethunter_kernel
          path: output/*
